version: 0.2

phases:
  install:
    runtime-versions:
       java: openjdk8
  build:
    commands:
       - echo "${CODEBUILD_WEBHOOK_HEAD_REF}"
       - aws s3 cp s3://nexuscredentials-cms/maven/settings.xml .
       - |
         if [ "${CODEBUILD_WEBHOOK_HEAD_REF}" = "refs/heads/develop" -o "${CODEBUILD_WEBHOOK_HEAD_REF}" = "refs/heads/master" ]; then
             mvn clean install deploy -s settings.xml
         else
             mvn clean install -s settings.xml
         fi

